#!/usr/bin/env bash
# intal nginx

if [ -e /var/run/nginx.pid ];
then
    apt-get -y update
    apt-get -y install nginx
    ufw allow  'Nginx HTTP' #on port 80
    echo "Hello World!" >/var/www/html/index.nginx-debian.html
    service nginx restart
else
    ufw allow  'Nginx HTTP' #on port 80
    echo "Hello World!" >/var/www/html/index.nginx-debian.html
    service nginx restart
fi


