#!/usr/bin/env bash
# Replace a line with multiple lines with sed

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP' #on port 80
echo "Hello World!" >/var/www/html/index.nginx-debian.html
sed -i 's+https://www.nginx.com/+g' /etc/nginx/sites-available/default
service nginx restart
