#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# Installed Nginx in our server
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
echo "Ceci n'est pas une page" > index404.html
sudo mv index.html /var/www/html/
sudo mv index404.html /var/www/html/
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a error_page 404 /index404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
