#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt -y update
sudo apt -y upgrade
sudo apt-get install -y haproxy
sudo sed -i "$ a\ENABLED=1" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\ \tlisten jhonpulido1990\n\tmode http\n\tbind *:80\n\tbalance roundrobin\n\tserver 3825-web-01 35.185.62.183:80 check\n\tserver 3825-web-02 35.237.143.24:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
