#!/usr/bin/env bash
#Write a Bash script that pings an IP address passed as an argument.
if ! ping -c1 "$@" &>/dev/null
then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        exit 1
fi
ping -c5 "$@"