#!/usr/bin/env bash
#Write a Bash script that pings an IP address passed as an argument.
length=${#@}
ip_address="$1"
if [[ "$length" -eq 0 ]]; then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
        ping -c5 "$ip_address"
fi
