#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
a=1
while ((a <= 100))
do
    if ((a%15 == 0))
    then
        echo "FizzBuzz"
    elif ((a%5 == 0))
    then
        echo "Buzz"
    elif ((a%3 == 0))
    then
        echo "Fizz"
    else
        echo $a
    fi
    ((a++))
done