#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times
a=1

while ((a <= 20))
do
    case $a in
        4) echo $a
            echo "bad luck from China";;
        9) echo $a
            echo "bad luck from Japan";;
        17) echo $a
            echo "bad luck from Italy";;
        *) echo $a;;
        esac
   ((a++))
done
