#!/usr/bin/env bash
#Write a Bash script that gives you information about the school
if [ -f "$school"]
then
    echo "school file exists"
    if [ -s "$school"]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
if [ -f "$school"]
then
    echo "school is a regular file"
fi