#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements
cp /etc/hosts /tmp.new
sed -i "s/^127.0.0.1/127.0.0.2/g" /tmp.new
echo "8.8.8.8 facebook.com" >> /tmp.new
cp -f /tmp.new /etc/hosts
