#!/usr/bin/env bash
# For the containers that you are given in this project as well as the checker, everything is run under the root user, which has the ability to run anything as another user.

sudo -u "$1" whoami
