#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
pkill nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
